### ISSUE TITLE
Best practices guide for editing Hugo menus in CloudCannon

### ISSUE THREAD

**Issue by rycoll** [CloudCannon/platform-documentation#72]
This will need to wait for an upcoming improvements on object inputs 👀 but it would be good to have a guide on how to best manage [Hugo menus](https://gohugo.io/content-management/menus/) in CloudCannon.

I'll moved over some starter content from Notion below 👇

---

We can use our Input Configuration and Structures.

After setting some configuration for menus in your Hugo config file, it then depends how you want to choose menus in each file.

## Simple Menu

Here’s an example for being able to choose what menus a file appears in:

`/content/about.md`

```yaml
---
menu:
  - footer
  - main
---
```

Then the `_inputs` configuration:

`/cloudcannon.config.yml`

```yaml
_inputs:
  menu:
    type: multiselect
    options:
      values:
        main: Heading menu
        footer: Footer
        aside: Right sidebar
```

That gives you this input:

![Untitled](https://github.com/CloudCannon/platform-documentation/assets/26177050/9fd54906-b2d7-4675-9e9a-52170fc70da4)

## Advanced menu:

This is the one with `weight` and `parent` keys:

`/content/about.md`

```yaml
---
menu:
  main:
    weight: 4
  footer:
    weight: 4
    parent: main
---
```

Once we have released support for adding keys to an object, you'll be able to configure something more flexible using the `allowed_keys` config:

`/cloudcannon.config.yml`

```yaml
_inputs:
  menu:
    type: object
    options:
      allowed_keys:
        - main
        - footer
        - aside
  menu.*:
    type: object
      options:
        structures:
          values:
            - label: Menu Item
              value:
                weight:
                parent:
  weight:
    type: number
  parent:
    type: select
    options:
      values:
        main: Heading menu
        footer: Footer
        aside: Right sidebar
```
