### ISSUE TITLE
Document `content_path` as a select `content_key` option

### ISSUE THREAD

**Issue by bglw** [CloudCannon/platform-documentation#86]
```
_inputs:
  my_select:
    type: select
    options:
      values: collections.some_collection
      value_key: content_path
```

Saves as `some_collection/about.md` rather than `content/some_collection/about/md`
